### ISSUE TITLE
QA_iiith_Structural dynamics

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#1]
Defect Description :
In Structural dynamics Lab,when we click on the lab it is redirecting to the lab page but the page is not completely reloading and the feature links are missing in the page ,where the page should be completely reloaded.

Actual Result :
In Structural dynamics Lab,when we click on the lab it is redirecting to the lab page but the page is not completely reloading and the feature links are missing in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers:Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5
![sd](https://cloud.githubusercontent.com/assets/14869397/13315161/3ebeb330-dbcf-11e5-885c-3d02f9e2651a.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Issue is closed now.
