### ISSUE TITLE
Broken logos in the Footer of Manual page_Torsional Response of Building

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#102]
@sadhanareddy In the Manual page of Torsional Response of Building, in the Footer the Face book, Twitter, LinkedIn and the You tube logos are broken. Need to update them.

**Comment by sadhanareddy** [comment]
Links are fixed. Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #102
