### ISSUE TITLE
QA_Introduction_Courses Aligned_Spelling mistakes_smk

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#103]
Defect Description :
In the Courses Aligned page of the Introduction section of this lab, found spelling mistakes.

Actual Result :
In the Courses Aligned page of the Introduction section of this lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i01](https://cloud.githubusercontent.com/assets/13479177/26351625/fdc351da-3fd5-11e7-8cdc-bd1a58131f3c.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still persisted. Hence re opened the issue.

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistake of Curriculum. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #103
