### ISSUE TITLE
QA_Simple Harmonic Oscillator_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#104]
Defect Description :
In the introduction page of Simple Harmonic Oscillator experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Simple Harmonic Oscillator experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i02](https://cloud.githubusercontent.com/assets/13479177/26388355/6829fc36-4071-11e7-87bf-7514603d8785.png)

**Comment by sravanthimodepu** [comment]
Ported the image in the introduction section from vlab.co.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #104
