### ISSUE TITLE
QA_Simple Harmonic Oscillator_Theory_Content-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#105]
Defect Description :
In the Theory page of Simple Harmonic Oscillator experiment, the content like formulas are missing. While porting special characters were not included. Where as the complete content can be found in vlab.co.in.

Functionality of the "Grade me" button is also not present.

Actual Result :
In the Theory page of Simple Harmonic Oscillator experiment, the content like formulas are missing. While porting special characters were not included. 
Functionality of the "Grade me" button is also not present.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i03](https://cloud.githubusercontent.com/assets/13479177/26388472/1c262e4e-4072-11e7-8484-7eff4893f17a.png)

**Comment by sravanthimodepu** [comment]
Added the missing images in the theory page of this experiment from vlab.co.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue still persisting. Hence re-opening the issue.

**Comment by sravanthimodepu** [comment]
Added the missing images in the theory page of this experiment from vlab.co.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #105
