### ISSUE TITLE
QA_Simple Harmonic Oscillator_Objective_improper-text-alignment

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#106]
Defect Description :
In the Objective page of Simple Harmonic Oscillator experiment, the text alignment is improper

Actual Result :
In the Objective page of Simple Harmonic Oscillator experiment, the text alignment is improper

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i04](https://cloud.githubusercontent.com/assets/13479177/26388530/72c0278c-4072-11e7-84cc-7ed03ece5f46.png)

**Comment by sravanthimodepu** [comment]
Aligned the content properly to view in a better way. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #106
