### ISSUE TITLE
QA_Simple Harmonic Oscillator_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#107]
Defect Description :
In the Manual page of Simple Harmonic Oscillator experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page. 

Actual Result :
In the Manual page of Simple Harmonic Oscillator experiment, the "Read More" link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i05](https://cloud.githubusercontent.com/assets/13479177/26388657/4b074e36-4073-11e7-8403-cc6e86c5f66b.png)

**Comment by sravanthimodepu** [comment]
Updated the appropriate link for **Read more** from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #107
