### ISSUE TITLE
QA_Simple Harmonic Oscillator_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#108]
Defect Description :
In the Manual page of Simple Harmonic Oscillator experiment, the " Manual video on Simple Harmonic Oscillator Experiment is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of Simple Harmonic Oscillator experiment, the " Manual video on Simple Harmonic Oscillator Experiment is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i06](https://cloud.githubusercontent.com/assets/13479177/26388722/a5117f5a-4073-11e7-881d-e9676af44466.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #108
