### ISSUE TITLE
QA_Simple Harmonic Oscillator_Quizzes_UI-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#109]
Defect Description :
In the Quizzes page of Simple Harmonic Oscillator experiment, the UI of the page is differing from the other labs.

Functionality of the "Grade me" button is also not present.

Actual Result :
In the Quizzes page of Simple Harmonic Oscillator experiment, the UI of the page is differing from the other labs. Different buttons are provided. In other labs Check and show answer buttons are given. Where as in this experiment of Structural dynamics lab while porting, the original buttons from vlabs page have been imported. 

Functionality of the "Grade me" button is also not present.
Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i07](https://cloud.githubusercontent.com/assets/13479177/26388889/972b27f0-4074-11e7-8656-4185d4fcc9de.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz questions in the Multiple Choice which is default quiz section in the open-edx. Initially quiz questions were ported in a html. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #109
