### ISSUE TITLE
QA_Simple Harmonic Oscillator_Manual_Spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#111]
Defect Description :
In the Manual page of the Simple Harmonic Oscillator experiment of this lab, found spelling mistakes.

Actual Result :
In the Manual page of the Simple Harmonic Oscillator experiment of this lab, found spelling mistakes.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i10](https://cloud.githubusercontent.com/assets/13479177/26389130/e9893d7e-4075-11e7-97ac-9598138cb456.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #111
