### ISSUE TITLE
QA_Simple Harmonic Oscillator_Further Readings_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#112]
Defect Description :
In the Further Readings page of Simple Harmonic Oscillator experiment, the 3rd link is broken. even in the vlabs.ac.in page also the link was broken.

Actual Result :
In the Further Readings page of Simple Harmonic Oscillator experiment, the 3rd link is broken. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i09](https://cloud.githubusercontent.com/assets/13479177/26389187/36acf87a-4076-11e7-96a6-fc0fc98d5621.png)

**Comment by sravanthimodepu** [comment]
Assigned the appropriate link for the 3rd link. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #112
