### ISSUE TITLE
QA_Simple Harmonic Oscillator_Feed-back_incorrect-assignment-of-feedback-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#113]
Defect Description :
In the Feedback page of Simple Harmonic Oscillator experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Actual Result : 
In the Feedback page of Simple Harmonic Oscillator experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i11](https://cloud.githubusercontent.com/assets/13479177/26389291/deb76c8a-4076-11e7-889f-1e11a5c0aef3.png)

**Comment by sravanthimodepu** [comment]
Updated the feedback link appropriate to the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #113
