### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#115]
Defect Description :
In the introduction page of Free Vibration of S.D.O.F System experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Free Vibration of S.D.O.F System experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i13](https://cloud.githubusercontent.com/assets/13479177/26389516/f5b97148-4077-11e7-8816-0fd1e723a12b.png)

**Comment by sravanthimodepu** [comment]
Added image in the introduction page of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #115
