### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Theory_Content-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#116]
Defect Description :
In the Theory page of Free Vibration of S.D.O.F System experiment, the content like formulas are missing. While porting special characters were not included. Where as the complete content can be found in vlab.co.in.

Actual Result :
In the Theory page of Free Vibration of S.D.O.F System experiment, the content like formulas are missing. While porting special characters were not included.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i14](https://cloud.githubusercontent.com/assets/13479177/26389615/6c4c9646-4078-11e7-9de8-1e8e61dbcef9.png)

**Comment by sravanthimodepu** [comment]
Added the missing images in the theory page of this experiment from vlab.co.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is fixed. Where as the word "where," repeated twice. Hence re-opening the issue.
![qa_oe_sd_i200](https://user-images.githubusercontent.com/13479177/27621791-d31429a0-5bf0-11e7-9df9-29bfd93b379a.png)

**Comment by sravanthimodepu** [comment]
Removed the word "where", which is repeated. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #116
