### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Theory_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#117]
Defect Description :
In the Theory page of Free Vibration of S.D.O.F System experiment, found broken link. Where as the link is navigating to appropriate page in vlab.co.in.

Actual Result :
In the Theory page of Free Vibration of S.D.O.F System experiment, found broken link. 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i15](https://cloud.githubusercontent.com/assets/13479177/26389724/f612ede4-4078-11e7-8726-4ca466ff9c7b.png)

**Comment by sravanthimodepu** [comment]
Assigned appropriate link for the  **Read more** from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #117
