### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#118]
Defect Description :
In the Manual page of Free Vibration of S.D.O.F System experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page.

Actual Result :
In the Manual page of Free Vibration of S.D.O.F System, the "Read More" link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i16](https://cloud.githubusercontent.com/assets/13479177/26389865/a122f332-4079-11e7-8f56-45941bf5be1e.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link for the **Read more ** from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #118
