### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#119]
Defect Description :
In the Manual page of Free Vibration of S.D.O.F System experiment, the " Manual video on Free Vibration of S.D.O.F System Experiment is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of Free Vibration of S.D.O.F System experiment, the " Manual video on Free Vibration of S.D.O.F System Experiment is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i17](https://cloud.githubusercontent.com/assets/13479177/26389923/e3361998-4079-11e7-8ee7-be2abdf03d2b.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #119
