### ISSUE TITLE
QA_Vibration Control_Introduction_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#12]
Defect Description :
In the Introduction page of "Vibration Control" experiment, the image links are disabled instead when we click on the image, it should redirect to a new tab  with the selected image displaying on the screen

Actual Result :
In the Introduction page of "Vibration Control" experiment, the image links are disabled in the page    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Vibration%20Control/Vibration%20Control_02_Introduction_smk.org

Attachment:
![sd90](https://cloud.githubusercontent.com/assets/14869397/14706240/2002fcde-07db-11e6-9ea1-cf0928bbb344.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, this is not the part of the experiment design.

**Comment by BSravanthi** [comment]
Issue is closed.
