### ISSUE TITLE
QA_Forced Vibration of S.D.O.F System_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#124]
Defect Description :
In the introduction page of Forced Vibration of S.D.O.F System experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Forced Vibration of S.D.O.F System experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i22](https://cloud.githubusercontent.com/assets/13479177/26390750/81be07da-407d-11e7-8fea-48c8e02869a4.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction section of this experiment. Hence resolve the issue.

**Comment by BSravanthi** [comment]
Closed #124
