### ISSUE TITLE
QA_Forced Vibration of S.D.O.F System_Theory_Content-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#125]
Defect Description :
In the Theory page of Forced Vibration of S.D.O.F System experiment, the content like formulae are missing. While porting special characters were not included. Where as the complete content can be found in vlab.co.in.

Actual Result :
In the Theory page of Forced Vibration of S.D.O.F System experiment, the content like formulae are missing. While porting special characters were not included.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i23](https://cloud.githubusercontent.com/assets/13479177/26390883/145e66de-407e-11e7-938c-f291b97a1f37.png)

**Comment by sravanthimodepu** [comment]
Added the link to the **Read more** from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #125
