### ISSUE TITLE
QA_Forced Vibration of S.D.O.F System_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#127]
Defect Description :
In the Manual page of **Forced Vibration of S.D.O.F System** experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page.

Actual Result :
In the Manual page of **Forced Vibration of S.D.O.F System** experiment, the "Read More" link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i25](https://cloud.githubusercontent.com/assets/13479177/26391224/60b965e6-407f-11e7-8f77-e06721099052.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to the **Read more** from the vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #127
