### ISSUE TITLE
QA_Forced Vibration of S.D.O.F System_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#128]
Defect Description :
In the Manual page of Free Vibration of S.D.O.F System experiment, the "Manual view on Forced Vibration of S.D.O.F system is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of Free Vibration of S.D.O.F System experiment, the "Manual view on Forced Vibration of S.D.O.F system is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i26](https://cloud.githubusercontent.com/assets/13479177/26391321/d04b09dc-407f-11e7-923c-08f7effe8dbd.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #128
