### ISSUE TITLE
QA_Forced vibration of S.D.O.F system_Feed-back_incorrect-assignment-of-feedback-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#131]
Defect Description :
In the Feedback page of Forced vibration of S.D.O.F system experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Actual Result :
In the Feedback page of Forced vibration of S.D.O.F system experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i29](https://cloud.githubusercontent.com/assets/13479177/26392942/e6b201f2-4085-11e7-83be-23e624ed9e40.png)

**Comment by sravanthimodepu** [comment]
Updated the feedback link appropriate to the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #131
