### ISSUE TITLE
QA_Impulse Response of S.D.O.F System_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#133]
Defect Description :
In the introduction page of Impulse Response of S.D.O.F System experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Impulse Response of S.D.O.F System experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i31](https://cloud.githubusercontent.com/assets/13479177/26393148/8b3a7b32-4086-11e7-81b8-f34fd9b01b80.png)

![qa_oe_sd_i32](https://cloud.githubusercontent.com/assets/13479177/26393158/991c2e1c-4086-11e7-983e-1787ea2c9ffd.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction page of this experiment from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #133
