### ISSUE TITLE
QA_Impulse Response of S.D.O.F system_Theory_Content-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#134]
Defect Description :
In the Theory page of Impulse Response of S.D.O.F system experiment, the graphical images are missing. While porting special characters were not included. Where as the complete content can be found in vlab.co.in.

Actual Result :
In the Theory page of Impulse Response of S.D.O.F system experiment, the graphical images are missing. While porting special characters were not included.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i33](https://cloud.githubusercontent.com/assets/13479177/26393293/04aed224-4087-11e7-9cea-cc1f0792bf6e.png)

**Comment by sravanthimodepu** [comment]
Added image in the theory page of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #134
