### ISSUE TITLE
QA_Concept of Response Spectrum_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#141]
Defect Description :
In the introduction page of Concept of Response Spectrum experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Concept of Response Spectrum experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i40](https://cloud.githubusercontent.com/assets/13479177/26394529/e0c26926-408a-11e7-8cad-c45f3d7226a6.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction page of this experiment from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #141
