### ISSUE TITLE
QA_Concept of Response Spectrum_Theory_Content-is-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#142]
Defect Description :
In the Theory page of Concept of Response Spectrum experiment, the formulae are missing. While porting special characters were not included. Where as the complete content can be found in vlab.co.in.

Actual Result :
In the Theory page of Concept of Response Spectrum experiment, the formulae are missing. While porting special characters were not included.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i41](https://cloud.githubusercontent.com/assets/13479177/26394676/5491462e-408b-11e7-9ddc-2617d2b5f0d8.png)

**Comment by sravanthimodepu** [comment]
Added images with special characters in the theory of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #142
