### ISSUE TITLE
QA_Concept of Response Spectrum_Theory_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#143]
Defect Description :
In the Theory page of Concept of Response Spectrum experiment, found broken link. Where as the link is navigating to appropriate page in vlab.co.in.

Actual Result :
In the Theory page of Concept of Response Spectrum experiment, found broken link.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i42](https://cloud.githubusercontent.com/assets/13479177/26397485/23733300-4094-11e7-80f0-cd57de5591b5.png)

**Comment by sravanthimodepu** [comment]
Added appropriate lin to **Read more** in the theory page of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #143
