### ISSUE TITLE
QA_Concept of Response Spectrum_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#144]
Defect Description :
In the Manual page of "Concept of Response Spectrum" experiment, the "Manual view on Concept of Response Spectrum is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of "Concept of Response Spectrum" experiment, the "Manual view on Concept of Response Spectrum is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i44](https://cloud.githubusercontent.com/assets/13479177/26395046/8beb02b2-408c-11e7-9f04-afa6c07a167a.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #144
