### ISSUE TITLE
QA_Concept of Response Spectrum_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#145]
Defect Description :
In the Manual page of **Concept of Response Spectrum** experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page.

Actual Result :
In the Manual page of **Concept of Response Spectrum** experiment, the "Read More" link is broken. Link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i43](https://cloud.githubusercontent.com/assets/13479177/26395189/eeac9668-408c-11e7-8cee-782ebcdead3e.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to the **Read more** from the vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #145
