### ISSUE TITLE
QA_Concept of Response Spectrum_Quizzes_UI-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#146]
Defect Description :
In the Quizzes page of Concept of Response Spectrum experiment, the UI of the page is differing from the other labs.

Functionality of the "Grade me" button is also not present.

Actual Result :
In the Quizzes page of Concept of Response Spectrum experiment, the UI of the page is differing from the other labs. Different buttons are provided. In other labs Check and show answer buttons are given. Where as in this experiment of Structural dynamics lab while porting, the original buttons from vlabs page have been imported.

Functionality of the "Grade me" button is also not present.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i45](https://cloud.githubusercontent.com/assets/13479177/26395846/fbcab814-408e-11e7-934a-20835a157717.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz questions in the Multiple Choice which is default quiz section in the open-edx. Initially quiz questions were ported in a html. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue re-opened. While testing the issue, found that the porting of 2nd question's options of quiz section was improper. Please find the attached for the details.
![qa_oe_sd_i195](https://user-images.githubusercontent.com/13479177/27620560-fe9b88b0-5be7-11e7-9389-db8711247932.png)

**Comment by sravanthimodepu** [comment]
Corrected the quiz questions in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #146
