### ISSUE TITLE
QA_Vibration of M.D.O.F System_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#152]
Defect Description :
In the Manual page of Vibration of M.D.O.F System experiment, the " Manual view on Vibration of M.D.O.F system is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of Vibration of M.D.O.F System experiment, the " Manual view on Vibration of M.D.O.F system is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i51](https://cloud.githubusercontent.com/assets/13479177/26397775/0f99382e-4095-11e7-9918-c15f7474c061.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #152
