### ISSUE TITLE
QA_Vibration of M.D.O.F System_Procedure_Content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#154]
Defect Description :
In the Procedure page of Vibration of M.D.O.F System experiment, the content says "The section will be updated soon". Need to either include the content or remove the section.

Actual Result :
In the Procedure page of Vibration of M.D.O.F System experiment, the content says "The section will be updated soon".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i53](https://cloud.githubusercontent.com/assets/13479177/26398039/e10fedee-4095-11e7-9696-68b1271360aa.png)

**Comment by sravanthimodepu** [comment]
As there is no content in the procedure, removing the procedure section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #154
