### ISSUE TITLE
QA_Vibration of M.D.O.F System_Further Readings_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#155]
Defect Description :
In the Further Readings page of Vibration of M.D.O.F System experiment, the 1st link is broken. even in the vlabs.ac.in page also the link was broken.

Actual Result :
In the Further Readings page of Vibration of M.D.O.F System experiment, the 1st link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i54](https://cloud.githubusercontent.com/assets/13479177/26398180/55c138aa-4096-11e7-9488-1d76458cdd40.png)

**Comment by sravanthimodepu** [comment]
As the link is not working, tried to get the experiment related link but unable to find the link. Hence removing the link.

**Comment by BSravanthi** [comment]
Closed #155
