### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Theory_Image-and-content-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#158]
Defect Description :
In the theory page of Behaviour of Rigid Blocks experiment, one image and a formula is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the theory page of Behaviour of Rigid Blocks experiment, one image and a formula is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i57](https://cloud.githubusercontent.com/assets/13479177/26399014/09ba9638-4099-11e7-8c34-5951a60993c6.png)

**Comment by sravanthimodepu** [comment]
Updated the page with image and the link from vlabs.ac.in Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #158
