### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Manual_spelling-mistakes

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#159]
Defect Description :
In the Manual page of Behaviour of Rigid Blocks experiment, found spelling mistakes

Actual Result :
In the Manual page of Behaviour of Rigid Blocks experiment, found spelling mistakes

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i59](https://cloud.githubusercontent.com/assets/13479177/26399593/1437179c-409b-11e7-98f5-b2f0816b611f.png)

**Comment by sravanthimodepu** [comment]
Corrected the spelling mistakes in the manual page of this experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #159
