### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#160]
Defect Description :
In the Manual page of **Behaviour of Rigid Blocks** experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page.

Actual Result :
In the Manual page of **Behaviour of Rigid Blocks** experiment, the "Read More" link is broken. Link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i60](https://cloud.githubusercontent.com/assets/13479177/26400131/30c6acae-409d-11e7-8031-6d247bc44699.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to the **Read more** from the vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #160
