### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Manual_unassigned-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#161]
Defect Description :
In the Manual page of Behaviour of Rigid Blocks experiment, the " Manual view on Vibration of M.D.O.F system is under construction" link is unassigned. Even in the vlabs.ac.in page the link is unassigned.

Actual Result :
In the Manual page of Behaviour of Rigid Blocks experiment, the " Manual view on Vibration of M.D.O.F system is under construction" link is unassigned.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i61](https://cloud.githubusercontent.com/assets/13479177/26400292/f620806a-409d-11e7-9f36-1f00435d64b6.png)

**Comment by sravanthimodepu** [comment]
Removed the content which is unassigned and it just says the video is under construction. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #161
