### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Procedure_Content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#163]
Defect Description :
In the Procedure page of Behaviour of Rigid Blocks experiment, the content says "The section will be updated soon". Need to either include the content or remove the section.

Actual Result :
In the Procedure page of Behaviour of Rigid Blocks experiment, the content says "The section will be updated soon".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i63](https://cloud.githubusercontent.com/assets/13479177/26400574/40e14e44-409f-11e7-90a5-04c572c5b0ad.png)

**Comment by sravanthimodepu** [comment]
As there is no content in the procedure, removing the procedure section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #163
