### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Further Readings_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#164]
Defect Description :
In the Further Readings page of Behaviour of Rigid Blocks experiment, the 1st link is broken. even in the vlabs.ac.in page also the link was broken.

Actual Result :
In the Further Readings page of Behaviour of Rigid Blocks experiment, the 1st link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i64](https://cloud.githubusercontent.com/assets/13479177/26400660/b9d16032-409f-11e7-82ce-9c12ec8bdc6a.png)

**Comment by sravanthimodepu** [comment]
As the link is not working, tried to get the experiment related link but unable to find the link. Hence removing the link.

**Comment by BSravanthi** [comment]
Closed #164
