### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Feed-back_incorrect-assignment-of-feedback-link 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#165]
Defect Description :
In the Feedback page of Behaviour of Rigid Blocks experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Actual Result :
In the Feedback page of Behaviour of Rigid Blocks experiment, On click, the feedback page should navigates to the existing experiment's feedback page. Where as the link is navigating to old feedback form.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i65](https://cloud.githubusercontent.com/assets/13479177/26400728/15311ca6-40a0-11e7-94cb-5d53d4299ca9.png)

**Comment by sravanthimodepu** [comment]
Updated the feedback link appropriate to the experiment. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #165
