### ISSUE TITLE
QA_improper-order-of-the-menu-items_Behaviour of Rigid Blocks

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#166]
Defect Description :
The order of the menu items for this experiment is not in desired order. Need to correct the order to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback".

Actual Result :
The order of the menu items for this experiment is not in desired order. The order of the menu items are given as "Introduction, Theory, Objective, Experiment, Manual, Quizzes, Procedure, Further readings, Feedback"

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachments:
![qa_oe_sd_i66](https://cloud.githubusercontent.com/assets/13479177/26400772/4eccf8f4-40a0-11e7-9a51-2516935f115e.png)

**Comment by sravanthimodepu** [comment]
Corrected the menu order of the experiments to "Introduction, Theory, Objective, Manual, Procedure, Experiment, Quizzes, Further readings and Feedback". Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #166
