### ISSUE TITLE
QA_Torsional Response of Building_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#167]
Defect Description :
In the introduction page of Torsional Response of Building experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Torsional Response of Building experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i67](https://cloud.githubusercontent.com/assets/13479177/26400999/53d56d12-40a1-11e7-92fe-49f9351bb921.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction page of this experiment from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #167
