### ISSUE TITLE
QA_Torsional Response of Building_Theory_content-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#168]
Defect Description :
In the theory page of **Torsional Response of Building** experiment, content is not included along with the images and special characters while porting. Formula is missing. The Image is available for this section in vlab.co.in.

Actual Result :
In the theory page of **Torsional Response of Building** experiment, content is not included along with the images and special characters while porting. Formula is missing.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i68](https://cloud.githubusercontent.com/assets/13479177/26401082/c3475dfe-40a1-11e7-8018-d2e380b842eb.png)

**Comment by sravanthimodepu** [comment]
Added images with special characters in the theory of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #168
