### ISSUE TITLE
QA_Torsional Response of Building_Manual_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#169]
Defect Description :
In the Manual page of **Torsional Response of Building** experiment, the "Read More" link is broken. Where as in vlabs.ac.in the link is redirecting to appropriate page.

Actual Result :
In the Manual page of **Torsional Response of Building** experiment, the "Read More" link is broken. Link is navigating to error page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i69](https://cloud.githubusercontent.com/assets/13479177/26401213/77a01ec6-40a2-11e7-948c-0d5a51fdd184.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to the **Read more** from the vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #169
