### ISSUE TITLE
QA_Torsional Response of Building_Procedure_Content-needs-to-be-updated

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#171]
Defect Description :
In the Procedure page of Torsional Response of Building experiment, the content says "The section will be updated soon". Need to either include the content or remove the section.

Actual Result :
In the Procedure page of Torsional Response of Building experiment, the content says "The section will be updated soon".

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i71](https://cloud.githubusercontent.com/assets/13479177/26401416/79aa7a8a-40a3-11e7-8ad1-da2df1b4462c.png)

**Comment by sravanthimodepu** [comment]
As there is no content in the procedure, removing the procedure section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #171
