### ISSUE TITLE
QA_Torsional Response of Building_Further Readings_broken-link 

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#172]
Defect Description :
In the Further Readings page of Torsional Response of Building experiment, the 2nd link is broken. even in the vlabs.ac.in page also the link was broken.

Actual Result :
In the Further Readings page of Torsional Response of Building experiment, the 2nd link is broken.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i72](https://cloud.githubusercontent.com/assets/13479177/26401521/03900a26-40a4-11e7-91c2-711ee7c7133d.png)

**Comment by sravanthimodepu** [comment]
As the link is not working, tried to get the appropriate link but did not found. Hence removing from the further readings page and resolved the issue.

**Comment by BSravanthi** [comment]
Closed #172
