### ISSUE TITLE
QA_Continuous Systems_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#175]
Defect Description :
In the introduction page of Continuous Systems experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Continuous Systems experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i75](https://cloud.githubusercontent.com/assets/13479177/26401868/77d83826-40a5-11e7-9e04-09a633d903cb.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction page of this experiment from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #175
