### ISSUE TITLE
QA_Continuous Systems_Theory_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#177]
Defect Description :
In the Theory page of Continuous Systems experiment, found broken link. Where as the link is navigating to appropriate page in vlab.co.in.

Actual Result :
In the Theory page of Continuous Systems experiment, found broken link.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i76](https://cloud.githubusercontent.com/assets/13479177/26402002/1f0da0a4-40a6-11e7-928f-ab1a3c73ec63.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to **Read more** in the theory of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #177
