### ISSUE TITLE
QA_Torsional Response of Building_Theory_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#178]
Defect Description :
In the Theory page of Torsional Response of Building experiment, found broken link. Where as the link is navigating to appropriate page in vlab.co.in.

Actual Result :
In the Theory page of Torsional Response of Building experiment, found broken link.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i78](https://cloud.githubusercontent.com/assets/13479177/26402134/ac840784-40a6-11e7-9508-8f33f5c4bb3b.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to **Read more** in the theory of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #178
