### ISSUE TITLE
QA_Behaviour of Rigid Blocks_Theory_broken-link

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#179]
Defect Description :
In the Theory page of Behaviour of Rigid Blocks experiment, found broken link. Where as the link is navigating to appropriate page in vlab.co.in.

Actual Result :
In the Theory page of Behaviour of Rigid Blocks experiment, found broken link.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i79](https://cloud.githubusercontent.com/assets/13479177/26402310/68b05502-40a7-11e7-953f-bf7ce0dbd5a8.png)

**Comment by sravanthimodepu** [comment]
Added appropriate link to **Read more** in the theory of this experiment from vlabs.ac.in page. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #179
