### ISSUE TITLE
QA_Vibration Control_Introduction_Image-missed

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#184]
Defect Description :
In the introduction page of Vibration Control experiment, the image is not included along with the content while porting. The Image is available for this section in vlab.co.in.

Actual Result :
In the introduction page of Vibration Control experiment, the image is not included along with the content while porting.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i84](https://cloud.githubusercontent.com/assets/13479177/26402779/41bfcb1a-40a9-11e7-9e3e-2ec0b0bc97ec.png)

**Comment by sravanthimodepu** [comment]
Added the image in the introduction page of this experiment from vlabs.ac.in . Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #184
