### ISSUE TITLE
QA_Vibration Control_Quizzes_UI-is-differing

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#186]
Defect Description :
In the Quizzes page of Vibration Control experiment, the UI of the page is differing from the other labs.

Functionality of the "Grade me" button is also not present.

Actual Result :
In the Quizzes page of Vibration Control experiment, the UI of the page is differing from the other labs. Different buttons are provided. In other labs Check and show answer buttons are given. Where as in this experiment of Structural dynamics lab while porting, the original buttons from vlabs page have been imported.

Functionality of the "Grade me" button is also not present.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i86](https://cloud.githubusercontent.com/assets/13479177/26402950/f1bdd11a-40a9-11e7-8219-858cf3b7a50f.png)

**Comment by sravanthimodepu** [comment]
Ported the quiz questions in the **Multiple Choice** which is default quiz section in the open-edx. Initially quiz questions were ported in a html. Hence resolved the issue.

**Comment by BSravanthi** [comment]
The issue is re opened as the functionality of check button is not present. Though the quiz section has ported properly.
Even the Show Answer button is needs to be added to quiz section.

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still persisting. Functionality of both the buttons is not found, hence reopening the issue.
