### ISSUE TITLE
QA_Continuous Systems_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#19]
Defect Description :
In the Objective page of "Continuous Systems" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen instead it should redirect to a new tab with the selected image displaying on the screen 

Actual Result :
In the Objective page of "Continuous Systems" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Continuous%20Systems/Continuous%20Systems_03_Objective_smk.org

Attachment:
![sd83](https://cloud.githubusercontent.com/assets/14869397/14705935/a8953906-07d9-11e6-86e7-cd7700089c6c.png)

**Comment by sadhanareddy** [comment]
On clicking image, it is not redirecting to blank page. Link for the image is not given as it is not the part of the design.

**Comment by BSravanthi** [comment]
Issue is closed.
