### ISSUE TITLE
QA_Torsional Response of Building_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#191]
Defect Description :
While testing issue #170 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #170 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i192](https://user-images.githubusercontent.com/13479177/27584205-beded4b8-5b54-11e7-90ae-5c7e632480d2.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still persisting, hence reopening the issue.
