### ISSUE TITLE
QA_Behaviour of Rigid Blocks _Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#192]
Defect Description :
While testing issue #162 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #162 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i193](https://user-images.githubusercontent.com/13479177/27584704-88f31484-5b56-11e7-8322-5634a8c518a4.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still persisting, hence reopening the issue.
