### ISSUE TITLE
QA_Vibration of M.D.O.F System_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#193]
Defect Description :
While testing issue #153 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #153 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i194](https://user-images.githubusercontent.com/13479177/27586457-07649ce6-5b5e-11e7-9db3-af893862b648.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still persisting, hence reopening the issue.
