### ISSUE TITLE
QA_Concept of Response Spectrum_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#194]
Defect Description :
While testing issue #146 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #146 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i196](https://user-images.githubusercontent.com/13479177/27620597-368b99b8-5be8-11e7-8279-6122dd834251.png)

**Comment by sravanthimodepu** [comment]
Check button and show answer buttons are enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Issue is still persisting, hence reopening the issue.
