### ISSUE TITLE
QA_Impulse Response of S.D.O.F System_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#195]
Defect Description :
While testing issue #137 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #137 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i197](https://user-images.githubusercontent.com/13479177/27620786-a86301b0-5be9-11e7-8e31-977c785ddc11.png)

**Comment by sravanthimodepu** [comment]
Check button in the quiz section is enabled. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Issue is still persisting, hence reopening the issue.
