### ISSUE TITLE
QA_Forced Vibration of S.D.O.F System_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#196]
Defect Description :
While testing issue #129 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #129 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i198](https://user-images.githubusercontent.com/13479177/27621324-9dc86296-5bed-11e7-9cdb-03830f780642.png)

**Comment by sravanthimodepu** [comment]
Check button is enabled in the quiz section. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Re opening the issue as the issue is still persisting.
