### ISSUE TITLE
QA_Free Vibration of S.D.O.F System_Quizzes_check-button-functionality

### ISSUE THREAD

**Issue by BSravanthi** [virtual-labs/structural-dynamics-iiith#197]
Defect Description :
While testing issue #120 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Actual Result :
While testing issue #120 found that the functionality of Check button is not present. Even show answer button is needs to be given.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i199](https://user-images.githubusercontent.com/13479177/27621592-7ec2c2fe-5bef-11e7-9cc0-d64afdffd919.png)

**Comment by sravanthimodepu** [comment]
Check button for the quiz section is enabled now. Hence the issue is resolved.

**Comment by BSravanthi** [comment]
Re opening the issue as still persisted
