### ISSUE TITLE
QA_Simple Harmonic Oscillator_Introduction_alignment-of-image-is-improper

### ISSUE THREAD

**Issue by BSravanthi** [Virtual-Labs/structural-dynamics-iiith#199]
Defect Description :
In the introduction page of "Simple Harmonic Oscillator", the alignment of the image is improper. The image is exceeding out of the screen.

Actual Result :
In the introduction page of "Simple Harmonic Oscillator", the alignment of the image is improper. The image is exceeding out of the screen.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

Attachment
![qa_oe_sd_i202](https://user-images.githubusercontent.com/13479177/27622858-4a05aed4-5bf7-11e7-8a08-645e68d8de74.png)

**Comment by sravanthimodepu** [comment]
Aligned the content and image in the center. Hence resolved the issue.

**Comment by BSravanthi** [comment]
Closed #199
