### ISSUE TITLE
QA_Continuous Systems_Introduction_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#20]
Defect Description :
In the Introduction page of "Continuous Systems" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen instead it should redirect to a new tab with the selected image displaying on the screen 

Actual Result :
In the Introduction page of "Continuous Systems" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen   

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Continuous%20Systems/Continuous%20Systems_02_Introduction_smk.org

Attachment:
![sd82](https://cloud.githubusercontent.com/assets/14869397/14705904/7b40ebee-07d9-11e6-80f1-1d338358a00a.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, this is not the part of the experiment design.

**Comment by sadhanareddy** [comment]
Issue is resolved now. On clicking image it is not redirecting to a blank page. Link to the image is not given, as this is not the part of the design.

**Comment by BSravanthi** [comment]
Closing the differed issue.
