### ISSUE TITLE
QA_Torsional Response of Building_Virtual lab_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#25]
Defect Description :
In the Virtual lab page of "Torsional Response of Building" experiment, when we click on the Virtual lab link it is redirecting to a blank page instead it should redirect to a new tab with the simulation process of the experiment 

Actual Result :
In the Virtual lab page of "Torsional Response of Building" experiment, when we click on the Virtual lab link it is redirecting to a blank page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Torsional%20Response%20of%20Building/Torsional%20Response%20of%20Building_09_Virtual%20lab_smk.org

Attachment:
![sd77](https://cloud.githubusercontent.com/assets/14869397/14705780/d81da808-07d8-11e6-8200-fd6be9701739.png)

**Comment by sadhanareddy** [comment]
Simulation is working. It requires Java 3D to run the simulation. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #25
