### ISSUE TITLE
QA_Torsional Response of Building_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#29]
Defect Description :
In the Objective page of "Torsional Response of Building" experiment, when we click on the Objective it redirecting to introduction page instead it should redirect to objective page 

Actual Result :
In the Objective page of "Torsional Response of Building" experiment, when we click on the Objective it redirecting to introduction page   

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Torsional%20Response%20of%20Building/Torsional%20Response%20of%20Building_03_Objective_smk.org

Attachment:
![sd73](https://cloud.githubusercontent.com/assets/14869397/14705674/50f345e0-07d8-11e6-952f-29d32aa85d7f.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
