### ISSUE TITLE
Simple Harmonic Oscillator_Manual

### ISSUE THREAD

**Issue by shivaansehgal** [virtual-labs/structural-dynamics-iiith#310]
Defect description :
Unnecessary new lines are inserted  

Expected result :
After observations read more should directly follow up rather than 6-7 new lines

Actual result :
![image](https://user-images.githubusercontent.com/44942355/54467853-cdd95f00-47ad-11e9-9a29-ece202f96cbc.png)

**Comment by samhithavootkoor** [comment]
commit id: 2810623

**Comment by somashekhar31** [comment]
vailidated-1 @samhithavootkoor

**Comment by shivaansehgal** [comment]
@samhithavootkoor  bhosidi issue resolve ke gaand mae bhut chull mach rahi h
