### ISSUE TITLE
Main-Logo-Link is broken

### ISSUE THREAD

**Issue by SiddarthVijay** [virtual-labs/structural-dynamics-iiith#371]
### Defect Description:
Clicking on the Logo of Vlabs should take us to the main page, but this link is broken
![broken_link](https://user-images.githubusercontent.com/31479595/54491015-fa41c800-48e0-11e9-9d63-e006cdc1a0cd.png)

**Comment by KanishAnand** [comment]
issue fix
commit id : https://github.com/virtual-labs/structural-dynamics-iiith/pull/394/commits/69dc3f43083f706e8873a14ef73daaea172a50db
