### ISSUE TITLE
QA_Behaviour of Rigid Block_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#38]
Defect Description :
In the Objective page of "Behaviour of Rigid Block" experiment, the image links are disabled instead when we click on the image, it should redirect to a new tab  with the selected image displaying on the screen

Actual Result :
In the Objective page of "Behaviour of Rigid Block" experiment, the image links are disabled in the page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Behaviour%20of%20Rigid%20Block/Behaviour%20of%20Rigid%20Block_03_Objective_smk.org

Attachment:
![sd64](https://cloud.githubusercontent.com/assets/14869397/14705312/7f9fb736-07d6-11e6-9c93-cbb60bde6ae2.png)

**Comment by sadhanareddy** [comment]
Differing this issue, as this not the part of the design

**Comment by BSravanthi** [comment]
Issue is closed.
