### ISSUE TITLE
QA_Vibration of M.D.O.F System_back to experiments_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#41]
Defect Description :
In the "Vibration of M.D.O.F System" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user..

Actual Result :
In the "Vibration of M.D.O.F System" experiment,the back to experiments link is not present in the page.    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Vibration%20of%20M.D.O.F%20System/Vibration%20of%20M.D.O.F%20System_16_back%20to%20experiments_p1.org

Attachment:
![sd61](https://cloud.githubusercontent.com/assets/14869397/14705254/3851fa2e-07d6-11e6-8901-ec913db58ca9.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Issue is closed.
