### ISSUE TITLE
QA_Vibration of M.D.O.F System_Alternate links-p2

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#42]
Defect Description :
In the Reference page of "Vibration of M.D.O.F System" experiment, when we click on cece.olin.edu/dynamics/assign/ps5_f08.pdf links present in the page,it is redirecting to a error page instead it should redirect to a new tab with the selected link.

Actual Result :
In the Reference page of "Vibration of M.D.O.F System" experiment, when we click on cece.olin.edu/dynamics/assign/ps5_f08.pdf links present in the page,it is redirecting to a error page.    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Vibration%20of%20M.D.O.F%20System/Vibration%20of%20M.D.O.F%20System_15_Alternate%20links-p2.org

Attachment:
![sd60](https://cloud.githubusercontent.com/assets/14869397/14705244/26e946ca-07d6-11e6-9756-b5c0de892240.png)

**Comment by sadhanareddy** [comment]
Commented out the link, as the link is not working.

**Comment by BSravanthi** [comment]
Closing the issue.
