### ISSUE TITLE
QA_Vibration of M.D.O.F System_Virtual lab_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#45]
Defect Description :
In the Virtual lab page of "Vibration of M.D.O.F System" experiment, when we click on the Virtual lab link it is redirecting to a Theory page instead it should redirect to a new tab with the simulation process of the experiment"

Actual Result :
In the Virtual lab page of "Vibration of M.D.O.F System" experiment, when we click on the Virtual lab link it is redirecting to a Theory page    

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Vibration%20of%20M.D.O.F%20System/Vibration%20of%20M.D.O.F%20System_09_Virtual%20lab_smk.org

Attachment:
![sd57](https://cloud.githubusercontent.com/assets/14869397/14705132/b89a761c-07d5-11e6-8d8c-0b99f397c87c.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Closed #45
