### ISSUE TITLE
QA_concept of Response Spectrum_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#51]
Defect Description :
In the "concept of Response Spectrum" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "concept of Response Spectrum" experiment,the back to experiments link is not present in the page.  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/concept%20of%20Response%20Spectrum/concept%20of%20Response%20Spectrum_15_Back%20to%20experiments_smk.org

Attachment:
![sd51](https://cloud.githubusercontent.com/assets/14869397/14705035/4e39f5fe-07d5-11e6-8a55-97ec9229d399.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Issue is closed.
