### ISSUE TITLE
QA_concept of Response Spectrum_virtual lab_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#54]
Defect Description :
In the Virtual lab page of "concept of Response Spectrum" experiment, when we click on the Virtual lab link it is redirecting to a blank page instead it should redirect to a new tab with the simulation process of the experiment

Actual Result :
In the Virtual lab page of "concept of Response Spectrum" experiment, when we click on the Virtual lab link it is redirecting to a blank page  

Environment :
Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/concept%20of%20Response%20Spectrum/concept%20of%20Response%20Spectrum_09_virtual%20lab_smk.org

Attachment:
![sd48](https://cloud.githubusercontent.com/assets/14869397/14704090/a052afc0-07d0-11e6-8025-ec8db62eb8fc.png)

**Comment by sadhanareddy** [comment]
Simulation is working. It requires Java 3D to run the simulation. Hence differing this issue.

**Comment by BSravanthi** [comment]
Closed #54
