### ISSUE TITLE
QA_concept of Response Spectrum_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#59]
Defect Description :
In the Introduction page of "concept of Response Spectrum" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen instead it should redirect to a new tab with the selected image displaying on the screen

Actual Result :
In the Introduction page of "concept of Response Spectrum" experiment,when we click on the image, it is redirect to a new tab with a blank page displayed on the screen 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/concept%20of%20Response%20Spectrum/concept%20of%20Response%20Spectrum_01_Usability_smk.org

Attachment:
![sd43](https://cloud.githubusercontent.com/assets/14869397/14703993/456a84fc-07d0-11e6-8300-d210059b5144.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, this is not the part of the experiment design.

**Comment by sadhanareddy** [comment]
Issue is resolved now. On clicking image it is not redirecting to a blank page. Link to the image is not given, as this is not the part of the design.

**Comment by BSravanthi** [comment]
Issue is closed.
