### ISSUE TITLE
QA_Impulse Response of SDOF_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#61]
Defect Description :
In the "Impulse Response of SDOF" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Impulse Response of SDOF" experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Impulse%20Response%20of%20SDOF/Impulse%20Response%20of%20SDOF_16_Back%20to%20experiments_smk.org

Attachment:
![sd41](https://cloud.githubusercontent.com/assets/14869397/14703948/19c69fca-07d0-11e6-97e8-6db508902482.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Issue is closed.
