### ISSUE TITLE
QA_Impulse Response of SDOF_Theory_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#66]
Defect Description :
In the Theory page of "Impulse Response of SDOF" experiment, when we click on all the links present in the page,they are redirecting to a blank page instead they should redirect to a new tab with the selected link

Actual Result :
In the Theory page of "Impulse Response of SDOF" experiment, when we click on all the links present in the page,they are redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5
 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Impulse%20Response%20of%20SDOF/Impulse%20Response%20of%20SDOF_06_Theory_smk.org

Attachment:
![sd36](https://cloud.githubusercontent.com/assets/14869397/14703844/9fff7de2-07cf-11e6-8a12-59b0f65943d9.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, read more is not taking much time to open the page.

**Comment by BSravanthi** [comment]
Issue is closed as the Read More link is redirecting to the concerned page.
