### ISSUE TITLE
QA_Forced Vibration of Single Degree of Freedom System_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#76]
Defect Description :
In the Objective page of "Forced Vibration of Single Degree of Freedom System" experiment, the image links are disabled instead when we click on the image, it should redirect to a new tab  with the selected image displaying on the screen

Actual Result :
In the Objective page of "Forced Vibration of Single Degree of Freedom System" experiment, the image links are disabled in the page  

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Forced%20Vibration%20of%20Single%20Degr/Forced%20Vibration%20of%20Single%20Degr_05_Objective_smk.org

Attachment:
![sd26](https://cloud.githubusercontent.com/assets/14869397/14703659/b683227c-07ce-11e6-8587-eaf16eaca41a.png)

**Comment by sadhanareddy** [comment]
Differing this issue, as this is not the part of the design.

**Comment by BSravanthi** [comment]
Issue is closed as this is a differed issue.
