### ISSUE TITLE
QA_Free Vibration of Single Degree of Freedom System_Back to experiments_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#81]
Defect Description :
In the "Free Vibration of Single Degree of Freedom System" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Free Vibration of Single Degree of Freedom System" experiment,the back to experiments link is not present in the page.     

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Free%20Vibration%20of%20Single%20Degree/Free%20Vibration%20of%20Single%20Degree_16_Back%20to%20experiments_smk.org

Attachment:
![sd21](https://cloud.githubusercontent.com/assets/14869397/14703574/1dce4250-07ce-11e6-8efa-dedf603297fb.png)

**Comment by sadhanareddy** [comment]
Issue is resolved now.

**Comment by BSravanthi** [comment]
Issue is closed.
