### ISSUE TITLE
QA_Free Vibration of Single Degree of Freedom System_Video_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#84]
Defect Description :
In the Video page of "Free Vibration of Single Degree of Freedom System" experiment, when we click on the video link it is redirecting to a blank page instead it should redirect to a new tab with the video displayed in the page

Actual Result :
In the Video page of "Free Vibration of Single Degree of Freedom System" experiment, when we click on the video link it is redirecting to a blank page     

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Free%20Vibration%20of%20Single%20Degree/Free%20Vibration%20of%20Single%20Degree_10_Video_smk.org

Attachment:
![sd18](https://cloud.githubusercontent.com/assets/14869397/14703510/cd2f9aa6-07cd-11e6-9377-ef0d60f55ec1.png)

**Comment by sadhanareddy** [comment]
After the conversion of the experiment to Ui-3.0, issue is resolved. Links for the flash videos are given in the Experiment tab.

**Comment by BSravanthi** [comment]
Closed #84
