### ISSUE TITLE
QA_Free Vibration of Single Degree of Freedom System_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#87]
Defect Description :
In the Objective page of "Free Vibration of Single Degree of Freedom System" experiment, the image links are disabled instead when we click on the image, it should redirect to a new tab with the selected image displaying on the screen

Actual Result :
In the Objective page of "Free Vibration of Single Degree of Freedom System" experiment, the image links are disabled in the page     

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Free%20Vibration%20of%20Single%20Degree/Free%20Vibration%20of%20Single%20Degree_05_Objective_smk.org

Attachment:
![sd15](https://cloud.githubusercontent.com/assets/14869397/14703397/46aba9c0-07cd-11e6-8116-f2bcb54de166.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, this is not the part of the experiment design.

**Comment by BSravanthi** [comment]
Issue is closed.
