### ISSUE TITLE
QA_Vibration Control_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#9]
Defect Description :
In the Objective page of "Vibration Control" experiment,when we click on the image, it is redirecting to a new tab with a blank page displayed on the screen instead it should redirect to a new tab with the selected image displaying on the screen

Actual Result :
In the Objective page of "Vibration Control" experiment,when we click on the image, it is redirecting to a new tab with a blank page displayed on the screen     

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Vibration%20Control/Vibration%20Control_04_Objective_smk.org

Attachment:
![sd93](https://cloud.githubusercontent.com/assets/14869397/14706296/63c5921a-07db-11e6-8ec5-17c53d1cf586.png)

**Comment by sadhanareddy** [comment]
On clicking image it is not redirecting to blank page. Link to the image is not given, as it is not the part of the design.

**Comment by BSravanthi** [comment]
Closing the differed issue.
