### ISSUE TITLE
QA_Simple Harmonic Oscillator_Virtual Lab_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#95]
Defect Description :
In the Virtual lab page of "Simple Harmonic Oscillator" experiment, when we click on the Virtual lab link it is redirecting to a blank page instead it should redirect to a new tab with the simulation process of the experiment

Actual Result :
In the Virtual lab page of "Simple Harmonic Oscillator" experiment, when we click on the Virtual lab link it is redirecting to a blank page   

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Simple%20Harmonic%20Oscillator/Simple%20Harmonic%20Oscillator_10_Virtual%20Lab_smk.org

Attachment:
![sd07](https://cloud.githubusercontent.com/assets/14869397/14703240/86018244-07cc-11e6-853f-49c93f979814.png)

**Comment by sadhanareddy** [comment]
Simulation is working. It requires Java3D to run the simulation. Hence differing this issue.

**Comment by BSravanthi** [comment]
Issue is closed.
