### ISSUE TITLE
QA_Simple Harmonic Oscillator_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/structural-dynamics-iiith#99]
Defect Description :
In the Objective page of "Simple Harmonic Oscillator" experiment, the image links are disabled instead when we click on the image, it should redirect to a new tab  with the selected image displaying on the screen

Actual Result :
In the Objective page of "Simple Harmonic Oscillator" experiment, the image links are disabled in the page   

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/structural-dynamics-iiith/blob/master/test-cases/integration_test-cases/Simple%20Harmonic%20Oscillator/Simple%20Harmonic%20Oscillator_04_Objective_smk.org

Attachment:
![sd03](https://cloud.githubusercontent.com/assets/14869397/14703183/3293430e-07cc-11e6-9912-54646dd6770d.png)

**Comment by sadhanareddy** [comment]
Differing this issue as, this is not the part of the experiment design.

**Comment by BSravanthi** [comment]
Issue is closed.
